In [53]:
import numpy as np
a=np.array([1,2,3,4]) #creating the array with one dimention using numpy
print(a)

[1 2 3 4]


In [66]:
a=np.array([[1,2,3,4,5,6,7,8,9,],[5,6,7,8,9,10,11,12,13]]) #creating the array with two dimention using numpy


In [55]:
#to get the dimension of array
a.ndim

2

In [56]:
# to get the shape of array (number of rows and columns)
print(a.shape)

(2, 3)


In [57]:
#to get the datattype of the array
print(a.dtype)

int64


In [58]:
#to get the size of the array
print(a.size)  #it will print the total number of elements in the array

6


In [59]:
#to get the specific item of an array [r,c]
print(a[1,2])

7


In [60]:
#to get the specific row of an array
a[1,:]

array([5, 6, 7])

In [61]:
# to print the specific column of an array
print(a[:,1])

[2 6]


In [ ]:
X=[1,2,3]
y=[4,5,6]

#print(a*b)
#we cannot multiply two lists in python but we can multiply two arrays in numpy

In [ ]:
# to get the sepecific little more fancy [startindex:stopindex:step
a[0,1:8:2] #row 0 columns from 1 to 8 with step 2

array([2, 4, 6, 8])

In [71]:
# 3D example 
i=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(i)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [74]:
#to access the specific item or modify
i[0,1,2]=90
i

array([[[ 1,  2,  3],
        [ 4,  5, 90]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
#initialize different types of array 

np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [84]:
np.ones([3,3,3] ,dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [86]:
np.full([2,3] ,88)

array([[88, 88, 88],
       [88, 88, 88]])

In [96]:
np.random.randint(0,10,(4,2,3)) #it will create the array of 4 rows and 2 columns with random values between 0 and 10

array([[[2, 2, 9],
        [6, 5, 4]],

       [[7, 5, 8],
        [8, 4, 9]],

       [[1, 2, 7],
        [3, 9, 0]],

       [[2, 8, 1],
        [7, 8, 7]]])

In [98]:
np.identity(6) #it will create the identity matrix of size 3x3

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [101]:
a=np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [104]:
#copying the array 
b=a.copy() #it will create the copy of the array a and assign it to b
b

array([1, 2, 3])

In [111]:
print(a+1)
print(a-1)
print(a*2)
print(a/2)
print(a**2)

[2 3 4]
[0 1 2]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]


In [120]:
#statistics with numpy
a=np.array([[1,2,3],[4,5,6]])
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.average(a))

1
6
21
3.5


In [129]:
#uploading the data from the file 

filedata=np.genfromtxt('data.txt',delimiter=",")
print(filedata)
filedata=filedata.astype('int32')
print(filedata)

filedata>50
filedata[filedata>=50]

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)