**series**
a series is a one dimentional labelled array that can hold any datatype 
like single coulmn in a spreadseet

In [4]:
import pandas as pd
data=[100.1,200.2,300,400]
series = pd.Series(data)
print(series)

0    100.1
1    200.2
2    300.0
3    400.0
dtype: float64


datatype mentioned below is the data type of the elements

we can change the index number also using the index[] here we can use the another list,tuple,string,another series

In [5]:
series=pd.Series(data,index=["a","b","c","d"])
print(series)

a    100.1
b    200.2
c    300.0
d    400.0
dtype: float64


Creating a DataFrame by passing a NumPy array with a datetime index using date_range() and labeled columns:


In [13]:
import numpy as np 
s=pd.date_range(20260611,periods=6)
s

df=pd.DataFrame(np.random.randn(6,4),index=s,columns=list("ABCD"))
df

,A,B,C,D
1970-01-01 00:00:00.020260611,-2.237780,0.241722,-0.574518,0.276088
1970-01-02 00:00:00.020260611,0.519536,0.870764,-0.438623,0.254755
1970-01-03 00:00:00.020260611,3.970815,0.357946,1.310072,1.192723
1970-01-04 00:00:00.020260611,-0.188420,-1.304055,-0.365650,-1.311440
1970-01-05 00:00:00.020260611,0.493993,0.535033,1.816363,0.840177
1970-01-06 00:00:00.020260611,1.292359,0.633950,1.853784,-0.700798


if we didn't mention any index it will take the index by defaukt in form of 1,2,3 
we can pass the dictionary with the key value pairs so key is considered as the column column label and values will be conoisdered as column value

Vewing data
Use DataFrame.head() and DataFrame.tail() to view the top and bottom rows of the frame respectively:

In [17]:
print(df.head(2))
print(df.tail())

                                      A         B         C         D
1970-01-01 00:00:00.020260611 -2.237780  0.241722 -0.574518  0.276088
1970-01-02 00:00:00.020260611  0.519536  0.870764 -0.438623  0.254755
                                      A         B         C         D
1970-01-02 00:00:00.020260611  0.519536  0.870764 -0.438623  0.254755
1970-01-03 00:00:00.020260611  3.970815  0.357946  1.310072  1.192723
1970-01-04 00:00:00.020260611 -0.188420 -1.304055 -0.365650 -1.311440
1970-01-05 00:00:00.020260611  0.493993  0.535033  1.816363  0.840177
1970-01-06 00:00:00.020260611  1.292359  0.633950  1.853784 -0.700798


Display the DataFrame.index or DataFrame.columns:

In [24]:
print(df.index)
print(df.columns)

DatetimeIndex(['1970-01-01 00:00:00.020260611',
               '1970-01-02 00:00:00.020260611',
               '1970-01-03 00:00:00.020260611',
               '1970-01-04 00:00:00.020260611',
               '1970-01-05 00:00:00.020260611',
               '1970-01-06 00:00:00.020260611'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='str')


Return a NumPy representation of the underlying data with DataFrame.to_numpy() without the index or column labels:

In [25]:
print(df.to_numpy())

[[-2.23777983  0.24172181 -0.57451849  0.27608764]
 [ 0.51953596  0.87076416 -0.43862321  0.25475498]
 [ 3.97081495  0.35794616  1.31007221  1.19272325]
 [-0.18841967 -1.30405525 -0.36565002 -1.31144011]
 [ 0.49399254  0.53503322  1.81636269  0.84017709]
 [ 1.29235933  0.63394966  1.85378358 -0.70079834]]


decribe() it shows the quick statistic summary of your data:
T --> transpose the data 

In [28]:
print(df.describe())
print(df.T)

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.641751  0.222560  0.600238  0.091917
std    2.026011  0.779269  1.178679  0.941266
min   -2.237780 -1.304055 -0.574518 -1.311440
25%   -0.017817  0.270778 -0.420380 -0.461910
50%    0.506764  0.446490  0.472211  0.265421
75%    1.099153  0.609221  1.689790  0.699155
max    3.970815  0.870764  1.853784  1.192723
   1970-01-01 00:00:00.020260611  1970-01-02 00:00:00.020260611  \
A                      -2.237780                       0.519536   
B                       0.241722                       0.870764   
C                      -0.574518                      -0.438623   
D                       0.276088                       0.254755   

   1970-01-03 00:00:00.020260611  1970-01-04 00:00:00.020260611  \
A                       3.970815                      -0.188420   
B                       0.357946                      -1.304055   
C                       1.310072                 

DataFrame.sort_index() sorts by an axis:

DataFrame.sort_values() sorts by values:

In [33]:
print(df.sort_index(axis=1,ascending=False))

                                      D         C         B         A
1970-01-01 00:00:00.020260611  0.276088 -0.574518  0.241722 -2.237780
1970-01-02 00:00:00.020260611  0.254755 -0.438623  0.870764  0.519536
1970-01-03 00:00:00.020260611  1.192723  1.310072  0.357946  3.970815
1970-01-04 00:00:00.020260611 -1.311440 -0.365650 -1.304055 -0.188420
1970-01-05 00:00:00.020260611  0.840177  1.816363  0.535033  0.493993
1970-01-06 00:00:00.020260611 -0.700798  1.853784  0.633950  1.292359


accessing the data by index name passing a single label slects the column
Passing a list of column labels selects multiple columns, which can be useful for getting a subset/rearranging:

passing a slice : selects matching rows:

In [38]:
print(df["A"])
print(df.A)
print(df[["A","B"]])
print(df[0:3])

1970-01-01 00:00:00.020260611   -2.237780
1970-01-02 00:00:00.020260611    0.519536
1970-01-03 00:00:00.020260611    3.970815
1970-01-04 00:00:00.020260611   -0.188420
1970-01-05 00:00:00.020260611    0.493993
1970-01-06 00:00:00.020260611    1.292359
Freq: D, Name: A, dtype: float64
1970-01-01 00:00:00.020260611   -2.237780
1970-01-02 00:00:00.020260611    0.519536
1970-01-03 00:00:00.020260611    3.970815
1970-01-04 00:00:00.020260611   -0.188420
1970-01-05 00:00:00.020260611    0.493993
1970-01-06 00:00:00.020260611    1.292359
Freq: D, Name: A, dtype: float64
                                      A         B
1970-01-01 00:00:00.020260611 -2.237780  0.241722
1970-01-02 00:00:00.020260611  0.519536  0.870764
1970-01-03 00:00:00.020260611  3.970815  0.357946
1970-01-04 00:00:00.020260611 -0.188420 -1.304055
1970-01-05 00:00:00.020260611  0.493993  0.535033
1970-01-06 00:00:00.020260611  1.292359  0.633950
                                      A         B         C         D
1970-01-01